-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 11:28:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Nomenclature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nomenclature` (
  `idNomenclature` CHAR(10) NOT NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idNomenclature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `id_article` INT NOT NULL,
  `ref_produit` VARCHAR(13) NULL,
  `nom_long` VARCHAR(45) NULL,
  `nom_court` VARCHAR(45) NULL,
  `nomenclature` CHAR(10) NULL,
  `sous_famille_distri_code` VARCHAR(3) NULL,
  `famille_distri_code` VARCHAR(3) NULL,
  `categorie_code` VARCHAR(2) NULL,
  `prix_achat` DOUBLE NULL,
  PRIMARY KEY (`id_article`),
  UNIQUE INDEX `code_UNIQUE` (`ref_produit` ASC) ,
  INDEX `nomenclature_fk_idx` (`nomenclature` ASC) ,
  CONSTRAINT `nomenclature_fk`
    FOREIGN KEY (`nomenclature`)
    REFERENCES `mydb`.`Nomenclature` (`idNomenclature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Magasin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Magasin` (
  `code_etablissement` CHAR(3) NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `code_postal` VARCHAR(5) NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`code_etablissement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temps` (
  `date` DATE NOT NULL,
  `id_date` CHAR(8) NOT NULL,
  `jour` VARCHAR(8) NULL,
  `code_mois` VARCHAR(2) NULL,
  `mois` VARCHAR(10) NULL,
  `trimestre` CHAR(1) NULL,
  `semestre` CHAR(1) NULL,
  `annee` CHAR(4) NULL,
  `jour_off` CHAR(1) NULL,
  `code_jour_off` CHAR(1) NULL,
  `vacances_zone_a` TINYINT NULL,
  PRIMARY KEY (`id_date`),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fait_Ventes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fait_Ventes` (
  `receipt_num` CHAR(10) NOT NULL,
  `receipt_date_id` CHAR(8) NULL,
  `receipt_hour` CHAR(4) NULL,
  `ref_produit` VARCHAR(13) NULL,
  `customer_code` CHAR(10) NULL,
  `department_code` VARCHAR(2) NULL,
  `store_id_code` CHAR(3) NULL,
  `description` VARCHAR(45) NULL,
  `price_level` CHAR(1) NULL,
  `purchased_price` DOUBLE NULL,
  `quantity` INT NULL,
  `amount` DOUBLE NULL,
  PRIMARY KEY (`receipt_num`),
  INDEX `magasin_fk_idx` (`store_id_code` ASC) ,
  INDEX `temps_fk_idx` (`receipt_date_id` ASC) ,
  INDEX `produit_fk_idx` (`ref_produit` ASC) ,
  CONSTRAINT `magasin_fk`
    FOREIGN KEY (`store_id_code`)
    REFERENCES `mydb`.`Magasin` (`code_etablissement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `temps_fk`
    FOREIGN KEY (`receipt_date_id`)
    REFERENCES `mydb`.`Temps` (`id_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `produit_fk`
    FOREIGN KEY (`ref_produit`)
    REFERENCES `mydb`.`Article` (`ref_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
